name: proof-of-build

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/proof-of-build.yml
      - PDAL-*.Dockerfile

jobs:

  liniapower-schemas-container:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pdal_version:
          - "2.7.2"
        debian_release:
          - "bookworm"

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build container
        run: |
          export REPOSITORY_NAME="pdal-${{ matrix.pdal_version }}-${{ matrix.debian_release }}"
          buildah bud -f PDAL-${{ matrix.pdal_version }}-${{ matrix.debian_release }}.Dockerfile -t ${REPOSITORY_NAME}
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          buildah push ${REPOSITORY_NAME} docker://ghcr.io/${{ github.repository }}/${REPOSITORY_NAME}:latest
